/*
 * This Java source file was generated by the Gradle 'init' task.
*/
package lego;

import lejos.robotics.RegulatedMotor;
import lejos.robotics.SampleProvider;
import lejos.hardware.Brick;
import lejos.hardware.BrickFinder;
import lejos.hardware.port.Port;
import lejos.utility.Delay;

public class App {
public static void main (String[] args) throws Exception {
        Bil bil = new Bil();

        Brick brick = BrickFinder.getDefault();
        Port fargePort = brick.getPort("S2"); // fargesensor
        Port fargePortKorrigering = brick.getPort("S4"); // fargesensor

        Farge fargeSensor = new Farge(fargePort);
        Farge fargeKorrigering = new Farge(fargePortKorrigering);

        float svart = fargeSensor.kalibrering();
        float hvit = fargeKorrigering.kalibrering();
        System.out.printf("%s - %s\n", svart, hvit);
        Thread.sleep(3000);

        float farge = 0;
        float fargeKorr = 0;

        // int topSpeed = 600;
        // int midSpeed = 400;
        // int minSpeed = 50;
        int topSpeed = 600;
        int midSpeed = 400;
        int minSpeed = 50;
        int accTopSpeed = 6000;
        int accMinSpeed = 3000;

        Retning retning;

        bil.A.setSpeed(topSpeed);
        bil.C.setSpeed(topSpeed);

        bil.A.setAcceleration(accTopSpeed);
        bil.C.setAcceleration(accTopSpeed);

        while (true) {
            farge = fargeSensor.getFarge();
            fargeKorr = fargeKorrigering.getFarge();

            if (farge > svart) {
                bil.A.setSpeed(midSpeed);
                bil.C.setSpeed(midSpeed);

                // bil.A.setAcceleration(accMinSpeed);
                // bil.C.setAcceleration(accMinSpeed);

                if (retning == Retning.FRAM) {
                    // Venstre
                    if (fargeKorr > svart) {
                        retning = 1;

                        // Høyre
                    } else if (fargeKorr < svart) {
                        retning = -1;
                    }
                } else  {
                    // Venstre
                    if (retning == Retning.VENSTRE) {
                        bil.A.setSpeed(minSpeed);
                        if (fargeKorr < svart) {
                            retning = 0;
                        }

                        // Høyre
                    } else if (retning == Retning.HØYRE) {
                        bil.C.setSpeed(minSpeed);
                    }
                }

            } else {
                retning = Retning.FRAM;

                bil.A.setSpeed(topSpeed);
                bil.C.setSpeed(topSpeed);

                bil.A.setAcceleration(accTopSpeed);
                bil.C.setAcceleration(accTopSpeed);
            }

            bil.A.forward();
            bil.C.forward();
        }
    }
}
