/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lego;

import lejos.robotics.RegulatedMotor;
import lejos.robotics.SampleProvider;
import lejos.hardware.Brick;
import lejos.hardware.BrickFinder;
import lejos.hardware.port.Port;

import lejos.hardware.Button;

public class App {
    public static void main (String[] args) throws Exception {
        Brick brick = BrickFinder.getDefault();

        Port fargePort = brick.getPort("S2"); // Hoved - fargesensor
        Port fargePortKorrigering = brick.getPort("S4"); // Korrigering - fargesensor

        Farge fargeSensor = new Farge(fargePort);
        Farge fargeKorrigering = new Farge(fargePortKorrigering);

        Bil bil = new Bil();

        boolean fortsett = false;
        float svart = 0;
        // 4 = Left
        // 3 = Right
        System.out.println("Da kan du velge!");
        do {
            int knapp = Button.waitForAnyEvent();

            if (knapp == Button.ID_RIGHT) {
                svart = fargeSensor.kalibrering();
                System.out.println("Ferdig kalibrert");
            } else if (knapp == Button.ID_LEFT) {
                fortsett = true;
                start(svart, fargeSensor, fargeKorrigering, bil);
            }else if (knapp == Button.ID_UP) {
                printFarge(fargeSensor, fargeKorrigering);
            } else if (knapp == Button.ID_DOWN) {
                fortsett = true;
            }
        } while (!fortsett);
    }

    public static void printFarge(Farge fargeSensor, Farge fargeKorrigering) {
        float farge = 0;
        float fargeKorr = 0;

        farge = fargeSensor.getFarge();
        fargeKorr = fargeKorrigering.getFarge();

        System.out.printf("%.3f - %.3f\n", farge, fargeKorr);
    }

    public static void start(float svart, Farge fargeSensor,
            Farge fargeKorrigering, Bil bil) {

        float farge = 0;
        float fargeKorr = 0;

        int topSpeed = 900;
        int midSpeed = 600;
        int minSpeed = 300;

        int accTopSpeed = 8000;
        int accMinSpeed = 4000;

        int retning = 0;

        bil.A.setSpeed(topSpeed);                    //Setter hastighet p� motorene
        bil.C.setSpeed(topSpeed);

        bil.A.setAcceleration(accTopSpeed);          //Setter akselerasjon til motorene
        bil.C.setAcceleration(accTopSpeed);

        while (true) {                               //While loop som kj�rer hele logikken
            farge = fargeSensor.getFarge();          //f�r inn fargen sensoren ser
            fargeKorr = fargeKorrigering.getFarge(); //f�r inn korrigeringen som blir laget vha fargen tidligere f�tt inn

            if (farge > svart) {
                bil.A.setSpeed(topSpeed);
                bil.C.setSpeed(topSpeed);

                // bil.A.setSpeed(midSpeed);
                // bil.C.setSpeed(midSpeed);
                // bil.A.setAcceleration(accMinSpeed);
                // bil.C.setAcceleration(accMinSpeed);

                if (retning == 0) {                  //if logikk for retning
                    // Venstre
                    if (fargeKorr > svart) {
                        retning = 1;

                                                     // Høyre
                    } else if (fargeKorr < svart) {
                        retning = -1;
                    }
                } else  {
                                                     // Venstre
                    if (retning == 1) {
                        bil.C.setSpeed(topSpeed);
                        if (farge > (svart + 5)) {
                            bil.A.setSpeed(minSpeed);
                        } else {
                            bil.A.setSpeed(midSpeed);
                        }

                        if (fargeKorr < svart) {
                            retning = 0;
                        }

                                                     // Høyre
                    } else if (retning == -1) {
                        bil.A.setSpeed(topSpeed);
                        if (farge > (svart + 5)) {
                            bil.C.setSpeed(minSpeed);
                        } else {
                            bil.C.setSpeed(midSpeed);
                        }
                    }
                }
            } else {
                retning = 0;

                bil.A.setSpeed(topSpeed);
                bil.C.setSpeed(topSpeed);

                // bil.A.setAcceleration(accTopSpeed);
                // bil.C.setAcceleration(accTopSpeed);
            }

            bil.A.forward();
            bil.C.forward();
        }
    }
}
