/*
 * This Java source file was generated by the Gradle 'init' task.
*/
package lego;

import lejos.robotics.RegulatedMotor;
import lejos.robotics.SampleProvider;
import lejos.hardware.Brick;
import lejos.hardware.BrickFinder;
import lejos.hardware.port.Port;
import lejos.utility.Delay;

public class App {
public static void main (String[] args) throws Exception {
        Bil bil = new Bil();

        Brick brick = BrickFinder.getDefault();
        Port fargePort = brick.getPort("S2");            // fargesensor
        Port fargePortKorrigering = brick.getPort("S4"); // fargesensor

        Farge fargeSensor = new Farge(fargePort);
        Farge fargeKorrigering = new Farge(fargePortKorrigering);

        float svart = fargeSensor.kalibrering();
        float hvit = fargeKorrigering.kalibrering();
        System.out.printf("%s - %s\n", svart, hvit);  //Printer ut informasjon hva sensoren ser for å troubleshoote
        Thread.sleep(3000);

        float farge = 0;
        float fargeKorr = 0;

        // int topSpeed = 600;
        // int midSpeed = 400;
        // int minSpeed = 50;
        int topSpeed = 600;
        int midSpeed = 400;
        int minSpeed = 50;
        int accTopSpeed = 6000;
        int accMinSpeed = 3000;

        int retning = 0;

        bil.A.setSpeed(topSpeed);                    //Setter hastighet på motorene
        bil.C.setSpeed(topSpeed);

        bil.A.setAcceleration(accTopSpeed);          //Setter akselerasjon til motorene
        bil.C.setAcceleration(accTopSpeed);

        while (true) {                               //While loop som kjører hele logikken
            farge = fargeSensor.getFarge();          //får inn fargen sensoren ser
            fargeKorr = fargeKorrigering.getFarge(); //får inn korrigeringen som blir laget vha fargen tidligere fått inn

            if (farge > svart) {                     //hvis fargen en ser er mindre enn svartverdien
                bil.A.setSpeed(midSpeed);
                bil.C.setSpeed(midSpeed);

                // bil.A.setAcceleration(accMinSpeed);
                // bil.C.setAcceleration(accMinSpeed);

                if (retning == 0) {                  //if logikk for retning
                    // Venstre
                    if (fargeKorr > svart) {
                        retning = 1;

                                                     // HÃ¸yre
                    } else if (fargeKorr < svart) {
                        retning = -1;
                    }
                } else  {
                                                     // Venstre
                    if (retning == 1) { 
                        bil.A.setSpeed(minSpeed);
                        if (fargeKorr < svart) {
                            retning = 0;
                        }

                                                     // HÃ¸yre
                    } else if (retning == -1) {
                        bil.C.setSpeed(minSpeed);
                    }
                }

            } else {                                 //hvis fargen en ser er lik eller større enn svartverdien
                retning = 0;                         //kjører rett fram

                bil.A.setSpeed(topSpeed);
                bil.C.setSpeed(topSpeed);

                bil.A.setAcceleration(accTopSpeed);
                bil.C.setAcceleration(accTopSpeed);
            }

            bil.A.forward();
            bil.C.forward();
        }
    }
}
